

SP_RENAME 'EMP','NEW_EMP'

--STRING FUNCTIONS

SELECT * from Student
SELECT LEN('WELCOME')
SELECT StdName,LEN(StdName) FROM Student

SELECT RTRIM('WELCOME   ')
SELECT LTRIM('   WELCOME')
SELECT LEN(RTRIM('WELCOME   '))
SELECT LEFT('WELCOME',3)
SELECT RIGHT('WELCOME',3)
SELECT SUBSTRING('WELCOME TO SQL SERVER',6,5)
SELECT UPPER('welcome'),LOWER('WELCOME')
SELECT REVERSE('WELCOME')
select REPLICATE('-',5)
SELECT ASCII('A')
SELECT CHAR(65)

SELECT GETDATE()

SELECT 
DAY(GETDATE()),
MONTH(GETDATE()),
YEAR(GETDATE())

SELECT DAY('11-DEC-2018')

SELECT 
DATEPART(HOUR,GETDATE()),
DATEPART(MINUTE,GETDATE()),
DATEPART(SECOND,GETDATE())

SELECT DATENAME(MM,GETDATE())
SELECT DATENAME(WEEKDAY,GETDATE())
SELECT DATEPART(DW,GETDATE())

SELECT DATENAME(DD,GETDATE()),DATENAME(YY,GETDATE())

SELECT DATEADD(DAY,10,GETDATE())
SELECT DATEADD(MONTH,3,GETDATE())
SELECT DATEADD(YEAR,3,GETDATE())

SELECT DATEADD(HOUR,2,GETDATE())
SELECT DATEADD(QUARTER,2,GETDATE())

SELECT DATEDIFF(YEAR,'9-DEC-1974',GETDATE())

SELECT CONVERT(CHAR(10),GETDATE(),101)

SELECT CONVERT(CHAR(10),GETDATE(),104)

SELECT '10' + '20'
SELECT CAST('10' AS INTEGER) + CAST('20' AS INTEGER)

SELECT ABS(-10),
POWER(2,3) AS POWER,
SQRT(49) as SQRT,
CEILING(142.23) as CEILING,
FLOOR(142.23) as FLOOR,
ROUND(142.2345,3) as ROUND,
ROUND(142.2343,3) as ROUND,
SIGN(10) as SIGN,
SIGN(-10) as SIGN

SELECT @@VERSION 
SELECT @@SERVERNAME
